{% set name = "sf-hamilton" %}
{% set version = "1.21.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sf-hamilton-{{ version }}.tar.gz
  sha256: eeefd067f58fd77e0a625eda5792339af97cc452d36232cbf4f19e635d18b627

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dataclasses
    - numpy
    - pandas
    - python >=3.6
    - typing_inspect

test:
  imports:
    - hamilton
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stitchfix/hamilton
  summary: Hamilton, the micro-framework for creating dataframes.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
