{% set name = "sf-hamilton" %}
{% set version = "1.27.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sf-hamilton-{{ version }}.tar.gz
  sha256: d1a5a4c153eb2bc18e767c2ce547e159dc5bfb3db9b08cca497c2e9bbc0a6a39

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4
  run:
    - numpy
    - pandas
    - python >=3.6,<4
    - typing_extensions >4.0.0
    - typing_inspect

test:
  imports:
    - hamilton
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DAGWorks-Inc/hamilton
  summary: Hamilton, the micro-framework for creating dataframes.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
