{% set name = "sf-hamilton" %}
{% set version = "1.21.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sf-hamilton-{{ version }}.tar.gz
  sha256: a53e0797cf85c1a4639330266cf86f66c7b9a67a84a634648f17de1184846c78

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dataclasses
    - numpy
    - pandas
    - python >=3.6
    - typing_inspect

test:
  imports:
    - hamilton
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stitchfix/hamilton
  summary: Hamilton, the micro-framework for creating dataframes.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
