{% set name = "sf-hamilton" %}
{% set version = "1.26.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sf-hamilton-{{ version }}.tar.gz
  sha256: 5965a4a0a6f6ce4573c2101b9a1d827653940466749517609248a2e0f955aee9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4
  run:
    - numpy
    - pandas
    - python >=3.6,<4
    - typing_extensions >4.0.0
    - typing_inspect

test:
  imports:
    - hamilton
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DAGWorks-Inc/hamilton
  summary: Hamilton, the micro-framework for creating dataframes.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
